# Generated by Django 4.1.6 on 2023-02-25 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Untitled', max_length=120, verbose_name='Title')),
                ('description', models.CharField(max_length=2048, verbose_name='Description')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reminder_set', models.BooleanField(default=False, verbose_name='isReminderSet')),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False, null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
